### ISSUE TITLE
Allow a semantics to be passed an input string OR a matchResult.

### ISSUE THREAD

**Issue by pdubroy** [harc/ohm#105]
Since a semantics instance is always associated with a particular, concrete grammar, we could support a shorthand that avoids calling `g.match`:

```
var g = ohm.grammar('Arithmetic { ... }');
s = g.semantics().addOperation('eval()', { ... });
s('1 + 2').eval();
```

If the input fails to match, I guess it would have to throw an exception.

**Comment by mroeder** [comment]
I guess that makes sense without the object matching now.

**Comment by pdubroy** [comment]
Don't think we need this — closing.
