### ISSUE TITLE
Visualizer: align input with corresponding parse tree node

### ISSUE THREAD

**Issue by lilyx** [harc/ohm#128]
Sometimes input segment and its corresponding parse tree node are not aligned correctly.
![2](https://cloud.githubusercontent.com/assets/2940370/16636902/fa0851e6-438f-11e6-8c6a-e3477327f609.jpg)

**Comment by pdubroy** [comment]
Saketh is investigating this.

**Comment by pdubroy** [comment]
This was fixed a long time ago.
