### ISSUE TITLE
Document semantic actions for listOf and friends

### ISSUE THREAD

**Issue by kkeri** [harc/ohm#133]
During writing semantics for my parser I realized from thrown exceptions that I should have defined `emptyListOf` and `nonemptyListOf` semantic actions, the latter having three arguments. A `listOf` action is also triggered, but I can't figure out the exact rules.

It would be useful to have some documentation on these actions.

**Comment by mroeder** [comment]
Thanks for point this out. We should add this to our documentation.
`nonemptyListOf` is defined in [built-in-rules.ohm](../blob/master/src/built-in-rules.ohm) as:
```
nonemptyListOf<elem, sep> = elem (sep elem)*
```
So it gets `(elem, [seps], [elems])` as arguments with the latter ones being array-like objects for `sep` and `elem`. An example for an action for `NonemptyListOf` can be found in the [visualizer example](../blob/master/examples/viz/index.html) and most often you would like to do something like:
```javascript
grammar.semantics().addOperation('myOp', {
  // ...
  nonemptyListOf: function(x, _, xs) {
    return [x.myOp()].concat(xs.myOp());  // .myOp can be called on the array-like xs
  }
  // ...
});
```

However, `listOf` only gets one arguments (see definition) that is either a `nonemptyListOf` or an `emptyListOf`. You usually don't want to intercept at this point and create arrays yourself here ;-).

**Comment by kkeri** [comment]
Thanks for your quick help. I was able to fix my semantics. I found that I still needed to implement `emptyListOf` like this:
~~~js
emptyListOf() {
	return [];
}
~~~
It's also remarkable that `(sep elem)*` is passed to the action as two distinct arrays, it was not obvious to me.

**Comment by pdubroy** [comment]
There's another, somewhat easier way to deal with `ListOf` expressions, which is (unfortunately) also not well documented -- `asIteration()`. As an example, take the following grammar:

```
G {
  Start = ListOf<letter, ",">
}
```
...and an operation defined as follows:

```
s.addOperation('myOp()', {
  Start: function(list) {
    return list.asIteration().myOp();
  },
  letter: function(l) {
    return this.interval.contents;
  }
});
```

Then `s(g.match('a, b, c')).myOp();` will return `['a', 'b', 'c']`.

**Comment by kkeri** [comment]
I finally chose `asIteration()` as I needed no more than a simple array.

**Comment by margh** [comment]
just ran into the same troubles, `asIteration()` worked perfectly.
I'm cranking out a demo using ohm atm, but next week I could try put in a PR for a bit of expanded documentation if you guys would like

**Comment by pdubroy** [comment]
@margh: Sounds good, thanks!

**Comment by pdubroy** [comment]
Closing this as it's now documented.
