### ISSUE TITLE
MatchResult.getDiscardedSpaces and lookahead

### ISSUE THREAD

**Issue by pdubroy** [harc/ohm#164]
I was looking at `MatchResult.getDiscardedSpaces` and noticed that the way it works is to assume that the discarded spaces cannot overlap with any Terminal nodes in the CST. But that's not true if a Terminal node appears inside a lookahead. For example:

```
  var g = testUtil.makeGrammar([
    'G {',
    '  Start = #("ab" &twoSpaces) "cd"',
    '  twoSpaces = "  "',
    '}']);

  var result = g.match('ab  cd').getDiscardedSpaces();
  t.equal(result._cst.children.length, 1);  // Fails -- actual length is 0.
```

It seems to me that the space between "ab" and "cd" should still be considered discarded space. @alexwarth, what do you think?

**Comment by pdubroy** [comment]
Also, now that we have built-in operations, I wonder if `getDiscardedSpaces` should actually be a built-in operation, rather than a method of MatchResult.

**Comment by pdubroy** [comment]
Hmmm, now that I think about this more:

- In a normal lookahead (`&`), the space is not really "discarded" -- it appears in the final CST. But it's _also_ skipped over by implicit space skipping.
- Inside negative lookahead (e.g., if I did `Start = ~("  " zz) "cd"` in the example above) it's both discarded, _and_ skipped over.

In the visualizer, "Show spaces" shows all the implicit `spaces` nodes that consumed any input. I feel like that should be consistent with whatever we want to do here.

**Comment by alexwarth** [comment]
Hi Pat, I see what you're saying. Can we talk about this on Monday, during our call, before we make any decisions / changes?

**Comment by pdubroy** [comment]
Closing this bug since `getDiscardedSpaces` has been removed.
