### ISSUE TITLE
Add "Common PEG Patterns" to documentation

### ISSUE THREAD

**Issue by pdubroy** [harc/ohm#169]
We should add a documentation page that covers common PEG patterns that new users might not be familiar with. E.g.:

- put keywords in their own rule, and use negative lookahead: `class = "class" ~identifierPart`
- using left recursion to implement operator precedence
- using negative lookahead to anything but a particular character (`~"x" any`)

etc.

**Comment by frankshearar** [comment]
I'd love to see an explanation in this page of the whys behind the patterns - for instance, that the negative lookahead is to avoid having to carefully order a prioritised choice to avoid prefixes appearing before longer strings (or to "maximally munch" tokens).

**Comment by pdubroy** [comment]
This is done now — see [Patterns and Pitfalls](https://github.com/harc/ohm/blob/master/doc/patterns-and-pitfalls.md).
