### ISSUE TITLE
Project mailing list

### ISSUE THREAD

**Issue by bzz** [harc/ohm#181]
Sorry if I missed that one, but as soon as this great project was moved to HARC, one can see that [mailing list was also moved](https://groups.google.com/a/cdglabs.org/forum/#!topic/ohm/XX-xvmBZJZM) but by looking around - it's very hard to say where exactly it was [moved to](https://github.com/harc/ohm/blob/master/CONTRIBUTING.md#before-submitting).

Is there a web UI for archive of the new mailing list? May be, following open source spirit of the project, it's worth mentioning a way to access it or how to subscribe in README or on project website.
Thanks in advance!

**Comment by pdubroy** [comment]
The mailing list (aka the Google Group) is linked from README.md; the new link is https://groups.google.com/a/ycr.org/forum/#!forum/ohm. I'll update the contributing guide to include that link as well.

You should also be able to access the list archives from the link above. Let me know if it doesn't work for some reason.

**Comment by nornagon** [comment]
That link is only available if you have an @ycr.org google account :(
