### ISSUE TITLE
AST from extras.toAST() is missing semantics

### ISSUE THREAD

**Issue by dundalek** [harc/ohm#186]
I am trying to build a library that would visualize Ohm grammars as railroad diagrams.

For this I need to traverse AST and map it to corresponding visual nodes. I use `extras.toAST()` to get the AST. However, it seems to be missing certain semantics like repetitions or lookahead.

For example this sample:
```js
var ohm = require('ohm-js');

var input = `Example {
  my_repetition
    = digit+

  my_lookahead
    = "(" (~")" any)* ")"
}
`

var ast = ohm.extras.toAST(ohm.ohmGrammar.match(input));
console.log(JSON.stringify(ast, null, 2));
```

Gives folowing AST. For example I don't see any indicator in the AST that the `digit` gets repeated.
```json
[{
  "0": "Example",
  "1": null,
  "3": [{
      "0": "my_repetition",
      "1": null,
      "2": null,
      "4": {
        "0": null,
        "1": [
          [{
            "0": "digit",
            "1": null,
            "type": "Base_application"
          }]
        ],
        "type": "RuleBody"
      },
      "type": "Rule_define"
    },
    {
      "0": "my_lookahead",
      "1": null,
      "2": null,
      "4": {
        "0": null,
        "1": [
          [
            "\"(\"", [
              [
                "\")\"",
                {
                  "0": "any",
                  "1": null,
                  "type": "Base_application"
                }
              ]
            ],
            "\")\""
          ]
        ],
        "type": "RuleBody"
      },
      "type": "Rule_define"
    }
  ],
  "type": "Grammar"
}]
```
I use the latest ohm version (0.12.3).

**Comment by dundalek** [comment]
Nevermind, I see it now.

**Comment by pdubroy** [comment]
Hi,

Glad to hear you found what were looking for, but I wanted to ask one thing: are you sure that you need an AST? One thing that makes Ohm different from most parsing tools is that you don't usually built an AST (which why `toAST` is under `extras`). Instead, you define operations/attributes which are a bit like writing a visitor over a _concrete_ syntax tree. See https://github.com/harc/ohm/blob/master/doc/api-reference.md#semantics-objects and the `examples/` dir for more info. For most uses this API is (we hope) better and simpler than generating an AST and manually walking it to get the information that you need.

**Comment by pdubroy** [comment]
You can find a good example of writing an operation here: https://jsfiddle.net/pdubroy/15k63qae/

**Comment by dundalek** [comment]
Thank you, you are right. I am used to build visitors over ASTs, but it should be totally doable and favorable to do it with semantic actions.

**Comment by pdubroy** [comment]
Great, if you have any questions feel free to ask on the [mailing list](https://groups.google.com/a/ycr.org/forum/#!forum/ohm). I'll close this issue for now, but if there's still an issue with `toAST()`, please feel free to re-open.
