### ISSUE TITLE
Add the `..` notation to the documentation 

### ISSUE THREAD

**Issue by rtoal** [harc/ohm#192]
I noticed in [this source file](https://github.com/harc/ohm/blob/master/src/built-in-rules.ohm) the following

      digit  (a digit)
        = "0".."9"

The `..` is used here, but it is not mentioned in [the documentation's syntax reference](https://github.com/harc/ohm/blob/master/doc/syntax-reference.md).

Is this an oversight, or is the `..` notation applicable _only_ to the built-in rules? If the intent is to make it available to everyone, I can write something up for the docs and submit a PR.

**Comment by pdubroy** [comment]
Hi Ray,

That is indeed an oversight! A PR adding documentation would be welcome.

**Comment by rtoal** [comment]
I started trying to write something up but I am not sure of the existing behavior.

Ohm allows me to write

```
C {
  c = "abc".."rst"
}
```

But it seems to treat it as the same as `"a".."r"`.

Also if I try to write:

```
C {
  c = "a"..last
  last = "x"
}
```

it says it expects `"` where the word `last` appears.

Perhaps if the intent is to allow only one-character terminals in double quotes on each side of the range operator, then maybe Ohm could enforce that before trying to document the feature? I'll be happy to contribute once there's some direction from the project maintainers.

**Comment by pdubroy** [comment]
Allowing only terminals is definitely the intended behaviour.

I think the current semantics is that if you have `<terminal1>..<terminal2>`, any string that is >= to terminal1 and <= terminal2 will match. I know at some point we discussed restricting it to only one-character terminals, but I can't remember what we decided, and unfortunately I can't find any issue related to it or anything in Slack.

@alexwarth, do you remember what we decided? Or any thoughts on whether we should stick with the current semantics?

**Comment by rtoal** [comment]
Looks like the <= / >= does not work for multicharacter terminals (see screenshot)
<img width="661" alt="screen shot 2017-03-06 at 7 58 13 am" src="https://cloud.githubusercontent.com/assets/538615/23617718/d81e3380-0242-11e7-925e-4739f055cb23.png">

**Comment by pdubroy** [comment]
Oh, you're right. I tested that this morning but I must have done something wrong.

I think we did end up deciding that it should only allow single characters -- that seems to be the assumption in `pexprs-eval.js`. So the bug here is that we should be throwing an error at grammar instantiation time if both ends of the range are not single character terminals.

**Comment by pdubroy** [comment]
Fixed: https://github.com/harc/ohm/commit/cb3fd3b2b98e65374d216a0271be005f8419709c
