### ISSUE TITLE
Throw error if Range is used with > 1 char Terminals

### ISSUE THREAD

**Issue by pdubroy** [harc/ohm#194]
The Range operator (`..`) could originally be used with terminals of any length, e.g. `"abc".."zz"`. Now, we only support 1-character ranges. However, we still allow grammars to contain ranges with any length of terminal. Instead, we should throw an error.

Original report from https://github.com/harc/ohm/issues/192.

**Comment by pdubroy** [comment]
go go @alexwarth 🔥

**Comment by alexwarth** [comment]
Betta reconize!
