### ISSUE TITLE
Change references to 'number' rule in the syntax reference to 'digit' rule

### ISSUE THREAD

**Issue by NAnguiano** [harc/ohm#197]
In the ohm syntax reference, it uses the `number` rule a few times. `number` doesn't appear to be a built-in rule at this time, so I believe it should be changed to the `digit` rule instead. 

This is minor, but it confused me a bit as an ohm newbie trying out everything in the syntax reference.

**Comment by alexwarth** [comment]
Good point -- thanks, Nicole! Fixed.
