### ISSUE TITLE
make script in readme file more readable

### ISSUE THREAD

**Issue by liadbiz** [harc/ohm#199]
I noticed that there are two scipts in readme looks like this:

<script type="text/markscript"> // The duplication here is required because Markscript only executes top-level code blocks. // TODO: Consider fixing this in Markscript. var ohm = require('ohm-js'); var myGrammar = ohm.grammar('MyGrammar { greeting = "Hello" | "Hola" }'); </script>

<script type="text/markscript"> markscript.transformNextBlock(function(code) { var trace = ohm.grammar('G { start = letter+ }').trace('ab'); assert.equal(trace.toString().trim(), code.trim()); }); </script>

maybe it will looks better in this way...

```js
<script type="text/markscript"> 
// The duplication here is required because Markscript only executes top-level code blocks. 
// TODO: Consider fixing this in Markscript.
var ohm = require('ohm-js'); 
var myGrammar = ohm.grammar('MyGrammar { greeting = "Hello" | "Hola" }'); 
</script>
```

**Comment by pdubroy** [comment]
You're proposing that we just remove the leading indentation, is that correct? Thanks for the suggestion, but I think I'm happy with the way it is currently.
