### ISSUE TITLE
Syntax highlighting bundle?

### ISSUE THREAD

**Issue by lazerwalker** [harc/ohm#200]
Hi!

As I'm editing my grammar file, I'd love to be able to get nice pretty syntax highlighting. I assume a sensible implementation of this would look something like a `tmbundle` file for `ohm` files (which would also let it be e.g. merged into the repo of syntax highlighting accepted by GitHub's online viewer). I'm happy to go down the rabbithole of throwing something together myself, but wanted to make sure I wasn't duplicating work. 

A quick search hasn't turned anything up, but has anything like this been done before?

**Comment by lazerwalker** [comment]
I found a lovely extension for VS Code, which suits my purposes nicely (looks like a fork of https://github.com/dlmanning/language-ohm). Closing :)

**Comment by pdubroy** [comment]
Sorry for not replying earlier. Glad you found what you needed! Can you link the version you found for VS Code? We should start putting together a list.

**Comment by lazerwalker** [comment]
Looks like it's https://github.com/attilah/ohm-vscode / https://marketplace.visualstudio.com/items?itemName=attilah.ohm
