### ISSUE TITLE
Wrong source contents

### ISSUE THREAD

**Issue by mlajtos** [harc/ohm#204]
I have encountered weird behaviour, or you know...bug.

Ohm version: 0.13.1
Node version: 8.1.0

```javascript
const ohm = require("ohm-js")

const g = ohm.grammar(`Mu{ List = NonemptyListOf<Item, ","> Item = alnum+ }`)
const s = g.createSemantics().addOperation("eval", {
    NonemptyListOf: (x, _, xs) => {
        return [x.eval(), ...xs.eval()]
    },
    Item: (value) => {
        return value.source.contents
    }
})
const r = g.match("Aloha, Hi")

console.log(s(r).eval())
// expected: [ 'Aloha', 'Hi' ]
// got: [ 'Aloha', 'Al' ]
```
If that's a feature I don't know what I am doing wrong.

**Comment by pdubroy** [comment]
Thanks for the bug report. That looks a lot like the bug that was fixed in 2e62fb6, but I guess there's still something wrong.

I'll try to look into this soon, but it's unlikely I'll be able to fix it before Monday.

**Comment by mlajtos** [comment]
Ok, I've look into it and figured that using normal function with return value ```this.sourceString``` is working, but using arrow function with ```value.sourceString``` is not. Using normal function with ```value.sourceString``` is also wrong.  Hope that helps.

Updated actions:
```javascript
{
    NonemptyListOf: function(x, _, xs) {
        return [x.eval(), ...xs.eval()]
    },
    Item: function(value) {
        return this.sourceString
    }
}
```

**Comment by pdubroy** [comment]
I wasn't able to reproduce this on the latest version of Ohm. Just to be sure, I've added a [test](https://github.com/harc/ohm/commit/07b7b3f1091d95b36f4c4fceda9e28154a393d3e) for this specific case.

**Comment by mlajtos** [comment]
Thank you. Glad to see Ohm moving forward!
