### ISSUE TITLE
version number in js

### ISSUE THREAD

**Issue by jcubic** [harc/ohm#210]
It would be nice to have access to version number from javascript, like `ohm.version`.
For now I fetch package.json file using ajax:

```javascript
$.get('https://rawgit.com/harc/ohm/master/package.json', function(json) {
    var term = $('body').terminal(parse, {
        greetings: '[[!;;;;https://github.com/harc/ohm]Ohm Parser] ' + json.version + ' demo'
    });
});
```
https://codepen.io/jcubic/pen/GMbZvz?editors=0010

**Comment by pdubroy** [comment]
Good idea! Done.
