### ISSUE TITLE
Add dynamic check for infinite loops

### ISSUE THREAD

**Issue by pdubroy** [harc/ohm#211]
From [Alex's comment](https://github.com/harc/ohm/issues/209#issuecomment-341698024) in issue 209:

> we should also implement a dynamic check that (say) throws an "bad kleene-* exception" when the expression under a Kleene-* succeeds w/o consuming any input. The message for this exception would explain that there is a problem in the grammar. What do you think?
>
> (The place where I'd add this dynamic check is pexprs.Iter.prototype.eval, when this.minNumMatches === 0.)

**Comment by alexwarth** [comment]
To clarify, this should really be an *error*, not just a match failure -- that way the author of the grammar will know that something is wrong, and will have a chance to fix it.

(Pull requests welcome!)
