### ISSUE TITLE
Is there an executable Ohm grammar for Markdown?

### ISSUE THREAD

**Issue by zaydek** [harc/ohm#213]
Seems like a good application. Does one exist? Thanks!

**Comment by pdubroy** [comment]
Not that I know of! Markdown is a bit tricky to parse, and I think that there are a few things that can't be easily done in a pure PEG-based tool like Ohm, such as indented code blocks. I think it's stuff that can be worked around though.

BTW, the best place to ask these kinds of questions is on the [mailing list](https://groups.google.com/a/ycr.org/forum/#!forum/ohm) — that way more people are likely to see your question and might be able to help out.
