### ISSUE TITLE
connection.rb:11: [BUG] Segmentation fault at 0x0000000000000000

### ISSUE THREAD

**Issue by rgaufman** [harc/ohm#216]
I'm not sure if this is ohm or redic related, when I run .first or [0] I get a segmentation fault, e.g.

```
[1] pry(main)> User.all
=> #<Ohm::Set:0x00007fd903c1e628 @key="User:all", @model=User, @namespace="User">
[2] pry(main)> User.all[0]
/usr/local/lib/ruby/gems/2.5.0/gems/redic-1.5.0/lib/redic/connection.rb:11: [BUG] Segmentation fault at 0x0000000000000000
```

The full details and log file is here: https://github.com/amakawa/redic/issues/12

Any ideas why this is happening?

My Ruby/Redis/Redic/Ohm versions are:
- ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
- Redis server v=4.0.9 sha=00000000:0 malloc=libc bits=64 build=e0c8d37381c486c6
- redic (1.5.0
- ohm (3.1.1)

**Comment by pdubroy** [comment]
I think you've got the wrong project — are you looking for [this one](https://github.com/soveran/ohm)?

**Comment by rgaufman** [comment]
Yes, sorry, my bad!
