### ISSUE TITLE
Building parser

### ISSUE THREAD

**Issue by sergeysova** [harc/ohm#221]
Can `ohm` build standalone parser like pegjs?

**Comment by sanboxrunner** [comment]
Yup

**Comment by sergeysova** [comment]
@sanboxrunner Can you show me example, or send me link?

**Comment by sanboxrunner** [comment]
Oh you mean a full standalone parser? Nope! It doesn't work like that!

**Comment by sanboxrunner** [comment]
It builds a parser dynamically for you as you run the program

**Comment by sergeysova** [comment]
Do you have plans for building standalone parser?

**Comment by pdubroy** [comment]
(Sorry for the extremely late reply; trying to clean up some older issues on here.)

There are no immediate plans to support creating standalone parsers like pegjs does. I think it should be possible to approximate that functionality by using a bundler like webpack or browserify.
