### ISSUE TITLE
Ignoring Redis fields that are missing in the model?

### ISSUE THREAD

**Issue by rgaufman** [harc/ohm#222]
When I change my model, any fields that are still present in Redis cause a NoMethodError, e.g.

```ruby
> Device.all.entries[0]
Traceback (most recent call last):
        2: from (irb):5
        1: from (irb):5:in `entries'
NoMethodError (undefined method `created_at=' for #<Device:0x0000000004c48278 @attributes={}, @_memo={}>)
```

Is there any way to get Ohm to ignore any fields from Redis that are not in the model? - or is there some other recommended strategy to handle this?

**Comment by mlajtos** [comment]
I believe you wanted [soveran/ohm](https://github.com/soveran/ohm) repo.

**Comment by rgaufman** [comment]
Yes I did, apologies!
