### ISSUE TITLE
Is it possible to get the string position of a node in a Semantic Action?

### ISSUE THREAD

**Issue by sanboxrunner** [harc/ohm#223]
Hi all,

I've never posted an issue before, and this might be the incorrect way to do it. I am building a parser for GML, the scripting language for GameMaker Studio 2 (and earlier iterations). Currently, I have it linting code in a Language Server (which runs through VSC) very well. There are, however, some issues -- right now it handles linting function calls (making sure the right number of arguments are called and that the function actually exists) through semantic actions -- obviously adding all the function names to the grammar seemed bad) and distinguishing certain variable types from each other. That works fine, but if there's an error, I need to send the position of the error to the user. How can I do that with only the node?
I was considering making an AST and then recusing up the AST, adding up the strings, but that doesn't seem like a smart idea (especially since I think I'll lose the white space).

Any help would be appreciated / pointing me to the correct resource or place to ask. Thank you!

**Comment by sanboxrunner** [comment]
Figured it out! For anyone looking -- it's node.source.startIdx and endIdx! I have gotten relatively familiar with this tool while using it over the last three weeks. I should spend the time helping with the docs..

**Comment by pdubroy** [comment]
Glad you figured it out!

And any contributions you have to improving the docs would be more than welcome.
