### ISSUE TITLE
Google Group Link

### ISSUE THREAD

**Issue by minemidnight** [harc/ohm#225]
I'm unable to join Ohm's Google Group. The link sends me to a page stating that I'm not authorized:

"This group is on a private domain.
Please sign in with an authorized account to view this content."

This authorized account must be ...@ycr.org google account. How can I get in this group?

**Comment by pdubroy** [comment]
It appears that the group is open for existing members, but closer to new members. I'm not sure what do to about this. Would be good to find an alternative place to host the mailing list.
