### ISSUE TITLE
How to write a grammar that support whitespace block like Python?

### ISSUE THREAD

**Issue by kelp404** [harc/ohm#233]
Hello,

This project is very good.
Could I ask a question?
I want to build a Python-like grammar.
But I don't known how to write a rule to define the block via space.

```
// This is the rule for JavaScript. I don't known how to write a rule for Python.
Block = "{" StatementList "}"
```

**Comment by dannypsnl** [comment]
Just define the token for space(` `) and tab (`\t`) then allow 0 to N token of space/tab, analysis how many tokens to know which block it's.

**Comment by kelp404** [comment]
I found Lexification to solve my issue.
https://github.com/harc/ohm/blob/master/doc/syntax-reference.md#lexification-

```
{
  Program = ObjectLiteral

  indent = "    " | "  " | "\t"
  PropertyAssignment = #(indent)? any ":\n"  ListOf<PropertyAssignment, "">
    | #(indent)? any ":" any

  ObjectLiteral = PropertyAssignment
}
```

```
a:
  b:
    x: 1
    y: 2
    z: 3
```
