### ISSUE TITLE
How can I turn an ohm grammar into something useable in vscode? (TextMate)

### ISSUE THREAD

**Issue by LiamKarlMitchell** [harc/ohm#236]
Is there a way to do this or to get ohm support vscode or do I just need to write a tmLanguage for the language I'm writing a gramma from as something separate?

Asking here, as google group link is private.

**Comment by ajbouh** [comment]
@justinmchase, I'm also looking to do this. Any pointers?

**Comment by justinmchase** [comment]
Simplest code snippet is maybe:
```
import { grammar } from 'ohm-js'
import { semantics } from './semantics' // see docs on how to implement this
import { interpret } from './interpretter' // interpret your own ast into action or data

const lang = fs.readFileSync(path.join(__dirname, 'lang.ohm'), 'utf8')
const G = grammar(lang)
const S = G.createSemantics().addOperation('ast', semantics)

const code = fs.readFileSync(path.join(__dirname, 'example.foo'))
const match = G.match(code)
if (match.succeeded()) {
  const ast = S(match).ast() // convert the parse ast into yours
  interpret(ast)
} else {
  console.error(match.message)
}
```

**Comment by ajbouh** [comment]
Thanks for the example code! I'm having trouble understanding how that plugs into the syntax highlighting logic of vscode. What am I missing?

**Comment by justinmchase** [comment]
Oh it doesn't. The ohm syntax highlighter just gives, in this case, `lang.ohm` some highlighting.

If you wanted to make a highlighter for _your own_ language files (e.g. "*.foo" files in this case) you'd have to make your own plugin and from there you could essentially just use this code snippet in your highligher plugin but you would skip the semantics parts and just use the grammar. The `match` object in this case has both a simple error message and a complex structure describing the entire parse tree and errors.

Also, most highlighters these days just use cheesy keyword and brace matching the rest is sort of bonus points, but you could theoretically use this to get a much more robust highlighting.

**Comment by ajbouh** [comment]
Ah, ok. There are some projects like https://github.com/codemirror/grammar-mode that seem promising. I was hoping you already had something like that working... :)

**Comment by ajbouh** [comment]
In case it's helpful to anyone else, I made some progress on this for CodeMirror-specific scenarios. I use incremental parsing to add and remove CSS classes on-the-fly using the markText(...) API. Happy to share code with anyone that's interested.
