### ISSUE TITLE
Question: Does Ohm offer optimization for static strings?

### ISSUE THREAD

**Issue by pmkary** [harc/ohm#241]
Hi! Sorry, I didn't know where else to ask this. 

What I'm trying to ask is this, Imagine we have something like this:

```
C = A | B
A = "(" x* ")"
B = "(" y* ")"
```

In most parser generators, people name the common static strings (`(` and `)` in this example) so that the parser generator can optimize on the commonality of the `(` and `)`. My question is do I have to do it in the Ohm, or will it internally do this?

**Comment by yoshikiohshima** [comment]
The general answer is "no, you don't have to". The memoization mechanism automatically recognizes that the string at a particular position is "(", then any subsequent attempt to match at the same position simply succeeds.

**Comment by pmkary** [comment]
@yoshikiohshima thanks a lot for you help
