### ISSUE TITLE
No support for Word Boundary (\b) in the Ohm

### ISSUE THREAD

**Issue by kharmadar** [harc/ohm#247]
Dear Ohm team, hi. Thanks a lot for reading this.

Most regular language systems have the `\b` command which lets them determine the word boundary.  This however is not the case with Ohm. Let's imagine the following formula:

<img src="https://user-images.githubusercontent.com/57100914/67883092-b0001500-fb58-11e9-8cf7-c86a17ce4060.png" width="300">

The problem here is that if you feed the grammar the identifier `format`, it will go to the identifier rule and since it will find `for` from the keyword rule, it will no longer continue. So there must be a way to add something after the keywords to make it differentiate:

<img src="https://user-images.githubusercontent.com/57100914/67883335-24d34f00-fb59-11e9-9861-12a97a6bbd27.png" width="350">
 
This solves the problem but the problem is that not necessarily all the grammar uses of the reserved keyword are followed by a space, this is an example that shows the need for word boundary detection in the tokenizer.

Do you have the tool or a substitute solution to this? if not, can you please implement it?

**Comment by pdubroy** [comment]
The typical way to handle this in a PEG is using negative lookahead after the keywords — e.g., [see our ES5 grammar](https://github.com/harc/ohm/blob/master/examples/ecmascript/es5.ohm#L209):

```
keyword = break | do | instanceof | typeof
    ...

break = "break" ~identifierPart
```
