### ISSUE TITLE
How to make this work?

### ISSUE THREAD

**Issue by panlina** [harc/ohm#254]
I have this grammar:

```
X {
  X = A | B
  A = "a"
  B = "a" "b"
}
```

When I try to match input `ab`, it reports `expected end of input`. I understand it's because alternation succeeds with the first match and later failure will not make it try another branch,
but is there any way to make it work like that?

**Comment by yoshikiohshima** [comment]
The choice operator (|) tries the second branch only when the first branch failed.  Here, "A" does match so X succeeds with input "a" consumed and "b" is left in the input.

It fails only at the end. No production rule fails but it does not consume all input and you get "Expect end of input" error.

I would recommend you to try it in the Ohm Editor.

**Comment by panlina** [comment]
Yes, I understand what's behind. Now I find the workaround of changing the `X` production to `X = A end | B end`.

**Comment by yoshikiohshima** [comment]
You can also change X to B | A.  Remember, match is greedy, and choice is ordered.  If the longer one is on the left hand of choice, and the shorter one is prefix of the longer one, making the longer one on the left is typically what you want.

**Comment by panlina** [comment]
That's what I come up with in the first place, but in my real application they are not prefix of each other, so I will still take the `X = A end | B end` way. Thanks.
