### ISSUE TITLE
How to allow identifiers with keywords as a prefix?

### ISSUE THREAD

**Issue by ApproximateIdentity** [harc/ohm#261]
Here I've produced a pretty simple example which demonstrates my issue:

`ident.ohm`
```
Ident {
    ident
        = ~keyword letter+
    keyword
        = "do" | "dont"
}
```

`identTest.js `
```js
const ohm = require("ohm-js");
const fs = require("fs");

const grammar = ohm.grammar(fs.readFileSync("./ident.ohm"));

console.log("Does it match?")

const testCases = [
    "do",
    "don",
    "dont",
    "doSomething",
    "daSomething"
];
var name, match;
for (key in testCases) {
    name = testCases[key];
    match = grammar.match(name, "ident").succeeded();
    console.log("\t", name, "-->", match)
}
```

If you run that test script you get the following:

```
$ node identTest.js
Does it match?
         do --> false
         don --> false
         dont --> false
         doSomething --> false
         daSomething --> true
```

So currently both `don` and `doSomething` do _not_ match even though I want them to. It's clear intuitively what's needed here (i.e. some requirement that a keyword "end"), but I haven't been able to sort it out. Is there something obvious I'm missing here?

Thanks for any help!

**Comment by justinmchase** [comment]
Try using the [`end` built-in rule](https://github.com/harc/ohm/blob/master/doc/syntax-reference.md#built-in-rules). 

e.g.
```ohm
Ident {
    ident
        = ~(keyword end) letter+
    keyword
        = "do" | "dont"
}
```

**Comment by ApproximateIdentity** [comment]
Thanks a lot that does  seem to fix it! I did need to make one other change though which is to list the keywords in the reverse order. E.g. changing the grammar to the following makes it work for me:

`ident.ohm`
```
Ident {
    ident
        = ~(keyword end) letter+
    keyword
        =  "dont" | "do"
}
```

I guess the issue is that having `do` first means that it will break out of the implicit case-matching earlier than intended. But for now this does not seem to be an issue for me. Thanks a lot!

**Comment by pdubroy** [comment]
@ApproximateIdentity Yes, we should probably have a FAQ about this, but this "earliest match first" behavior is intended, and it's inherent to the way PEG-based parsers (like Ohm) work. You can read more about it here: https://en.wikipedia.org/wiki/Parsing_expression_grammar#Ambiguity_detection_and_influence_of_rule_order_on_language_that_is_matched
