### ISSUE TITLE
Expose getLineAndColumn?

### ISSUE THREAD

**Issue by stagas** [harc/ohm#281]
We are exposing [`util.getLineAndColumnMessage()`](https://github.com/harc/ohm/blob/f0a893440a151aa04952ac15bd8d7f4b4b824aca/ohm-js/src/util.js#L112) in the `Interval` instances, but I think it would be useful to expose [`util.getLineAndColumn()`](https://github.com/harc/ohm/blob/f0a893440a151aa04952ac15bd8d7f4b4b824aca/ohm-js/src/util.js#L56) as well. I can prepare a PR if necessary. Thoughts?

https://github.com/harc/ohm/blob/f0a893440a151aa04952ac15bd8d7f4b4b824aca/ohm-js/src/Interval.js#L52-L55

**Comment by pdubroy** [comment]
@stagas Sounds reasonable to me. Where are you thinking of putting it? My first thought would be to put it in `extras`.

I assume you are thinking that this is useful for language authors (?)

**Comment by stagas** [comment]
I was thinking just adding a method right next to that one in the `Interval`, exactly the same except it calls `util.getLineAndColumn()`. It's useful when doing your own reflections, managing the way you display the error in an editor or elsewhere but there could be more cases and since we're already doing it for `util.getLineAndColumnMessage()`. Okay, now that I look up the docs I see that `Interval` isn't documented - which is what I was accessing inside the visitor from `.source`, so maybe these are not meant to be public, but I couldn't find any other way to get to the line and number properties but only by adding that method. Is there another way to go about it maybe?

**Comment by pdubroy** [comment]
Sorry, I misunderstood. Sounds good to me, and a PR would be very much appreciated!

IMO `Interval` can be considered public. I don't think it was a deliberate choice not to document it, just that our documentation is not exhaustive :-)

**Comment by stagas** [comment]
Alright, good to know about `Interval` being public! I will see when I can get to it for the PR, meanwhile to give you an idea for what I'm doing exactly is I am saving meta information of the node for the output tree so I can have reflection, here's the snippet copy paste but you will understand:

```js
function meta (src) {
  const _meta = { node: src }
  if (src.source) {
    // TODO: this is inefficient
    _meta.pos = src.source.getLineAndColumn()
    _meta.message = src.source.getLineAndColumnMessage()
  }
  return { _meta }
}
```

which isn't also very good because I need to do both these calls to get the position and the message, but it's not so horrible, and maybe what I'm doing isn't common case. Ideally `getLineAndColumnMessage()` would return an object with the line and column results(since it has them) plus the message so there isn't a need to do it twice. But, that would break existing implementations that depending on it being a string, so this could maybe be refactored in the future (or one horrible idea I had now is to use a string **object** as; `message = new String(sb.contents()); message.lineNum = lineNum; message.colNum = colNum` and return that.. that reminds me of es3, i think the regexp is doing something similar, with properties in a string xD.

**Comment by pdubroy** [comment]
What about adding a `toString()` method to the object returned by `getLineAndColumn()`? Then `getLineAndColumnMessage()` could be changed to call that (and you would only have to store the result of `getLineAndColumn()`).

Btw, if you are doing this for every node maybe it is simpler to keep a reference to the Interval itself?

**Comment by stagas** [comment]
> What about adding a `toString()` method to the object returned by `getLineAndColumn()`? Then `getLineAndColumnMessage()` could be changed to call that (and you would only have to store the result of `getLineAndColumn()`).
> 

That's a great idea. I can do it, on this PR and we change the titles or you want a new one?


> Btw, if you are doing this for every node maybe it is simpler to keep a reference to the Interval itself?

ah yes, that would be better! thanks!

**Comment by stagas** [comment]
sorry i mean, on the PR i linked, i thought this was the PR discussion :)

**Comment by pdubroy** [comment]
I'm happy either way — we can either merge the existing PR and implement `toString()` in a new one, or just the existing PR. Thanks!

**Comment by pdubroy** [comment]
I've merged the PR, but let's keep this open until we implement the `toString()` as discussed above.

**Comment by stagas** [comment]
> I've merged the PR, but let's keep this open until we implement the `toString()` as discussed above.

You beat me for a few seconds :) I did a new PR, the diff isn't helping but it's the same method pulled to a util.

**Comment by pdubroy** [comment]
Just merged the PR. @stagas , would you like me to do a release?

One minor thing that I'm thinking about is that it's maybe a bit unusual for `toString()` to take arguments. Though, since they're optional, it's perfectly valid. What do you think?

An alternative would be another method called `toStringHighlightingRanges(...ranges)` or something.

**Comment by stagas** [comment]
Thanks! 

> would you like me to do a release?

I'm not in a hurry for a release, but thanks :)

> maybe a bit unusual for `toString()` to take arguments

Yes, I had the concern as well, ideally this needs to be a `class` object with methods but practically it doesn't matter because it becomes a hidden class (which is why I pulled the method out and used it as a reference). It's not too uncommon for `toString()` to take arguments, JavaScript has it for the `Number` class at least, `(10).toString(16) === 'a'`, Node's Buffer has it as well (from the docs: `buf.toString([encoding[, start[, end]]])`) and I've seen it in other libs. I think generally the `toSomething()` are methods and not getters because they expect to receive modifier arguments.

So I wouldn't go for another method for the what is essentially the same function, I think if it's simply documented it would be fine.

**Comment by pdubroy** [comment]
Perfect, then I'm totally happy with this! I appreciate the examples btw — I tried to find some but couldn't find / think of any.

Thanks again for the contribution, and for the productive discussion too :-)

**Comment by stagas** [comment]
Hey thank you for the great project! I'm definitely feeling the Ohm vibe knowing that my syntax is logically proved :D
