### ISSUE TITLE
How to get any text  inside parentheses?

### ISSUE THREAD

**Issue by kassadin** [harc/ohm#287]
Just like `get(any text)`, which is text inside,may be contains `'('  ')'`,so can't use  `(~")" any)*` .
I can do it with regular expressions, but how can I do it with ohm?
![ohm](https://user-images.githubusercontent.com/1104051/107955000-2f2c8d00-6fd8-11eb-801b-817001208b3a.jpg)

![regexr](https://user-images.githubusercontent.com/1104051/107954921-1328eb80-6fd8-11eb-8f90-51c72a0e31ae.jpg)

**Comment by pdubroy** [comment]
It depends on exactly what your language needs to support, but does including `end` in your lookahead help?

E.g.:

```
Text = "get" "(" parenthesized ")"
parenthesized = (~(")" end) any)*
```

**Comment by kassadin** [comment]
Great!
I didn't realize that `~` could act on Sequence, I tried many times before in `~(a|b)`, now I can continue
Thank you.

**Comment by alexwarth** [comment]
Note that

```
parenthesized = (~(")" end) any)*
```

can be simplified to

```
parenthesized = (~")" any)*
```

(The `end` is not necessary b/c `any` does not succeed at the end of the file.)
