### ISSUE TITLE
[Feature Request] Support for repeatition range

### ISSUE THREAD

**Issue by MuhammedZakir** [harc/ohm#310]
As in regex : `e {start,end}`. Of course, syntax can be different.

Specifically, I want to choose the rules based on the count of next element. For now, I hardcode the repeatition and use alternative expression. But that seems suboptimal?

**Comment by MuhammedZakir** [comment]
Sorry, I didn't know there was already a discussion about this [1]. I see you have mentioned using semantic action. I personally think having a repeatition range operator inside grammar is better. Using semantic actions for this feel a bit "hacky" to me.

When using AST transformer for cases like this, can I use functions/conditions to change the node type?

[1] https://github.com/harc/ohm/discussions/280

**Comment by pdubroy** [comment]
@MuhammedZakir Can you add some more details about your use case to #215?
