### ISSUE TITLE
fast-glob is missing in the @ohm-js/cli/package.json

### ISSUE THREAD

**Issue by pragdave** [harc/ohm#321]
I'd generate a PR, but I'm not sure where this lives in the v16 world.

Dave

**Comment by pdubroy** [comment]
Whoops, thanks for the report! Must have worked locally because it was used in the now-deleted `typescript-codegen` package, so it was still in yarn.lock.

Anyways, fixed on master, and I've pushed a new version (0.1.1) of the `@ohm-js/cli` package.
