### ISSUE TITLE
What the heck is arity, arity inconsistency and what will cause throwing this error?

### ISSUE THREAD

**Issue by StephenChips** [harc/ohm#328]

**Comment by pdubroy** [comment]
Please take a look at the [documentation on semantic actions](https://github.com/harc/ohm/blob/master/doc/api-reference.md#semantic-actions). Hopefully this clarifies things. If you have more questions, please feel free to ask on the [discussions page](https://github.com/harc/ohm/discussions) or [Discord](https://discord.gg/KwxY5gegRQ).

**Comment by romannurik** [comment]
FWIW I was getting this error and adding a a `caseName` fixed it... i.e. the `-- plus` in the math example. My first thought was it was OHM's commenting syntax, but it's not :)

**Comment by pdubroy** [comment]
Hi @romannurik! I think the best documentation we have on arity and case names is in the tutorial: https://nextjournal.com/dubroy/ohm-parsing-made-easy#case-labels-and-arity. Does this clarify things?

We should put this (or something like it) into the API reference too.

**Comment by romannurik** [comment]
Oh I didn't come across that doc, that's helpful !

FWIW so far it's been a great experience :-) thanks for building this!

**Comment by pdubroy** [comment]
Glad you're enjoying it. I'd be curious to hear what you're doing with it, if you feel like sharing! Feel free to DM me on Twitter if you don't want to go into details right here :-)

**Comment by romannurik** [comment]
I'll ping you on Twitter primarily to avoid spamming this issue thread not because it's anything private :-)
