### ISSUE TITLE
Issues with "Ohm: Parsing Made Easy" article

### ISSUE THREAD

**Issue by customcommander** [harc/ohm#338]
Hi,

Re: https://nextjournal.com/dubroy/ohm-parsing-made-easy

First I want to say that this article is amazing. It got me super excited to trying out Ohm!

As I was reading through I noticed a couple of things:

**Broken code runner?**

This is just one example:

![Screenshot 2021-11-16 at 09 59 19](https://user-images.githubusercontent.com/681975/141964990-5bdf4baa-3c3e-4c8c-8e96-46df43458b7f.png)

**Repeated list items**
![Screenshot 2021-11-16 at 09 59 57](https://user-images.githubusercontent.com/681975/141965120-9cbe4754-9c01-476d-a34b-139f230e5fa0.png)

**Repeat list items + one dead link**

![Screenshot 2021-11-16 at 10 00 38](https://user-images.githubusercontent.com/681975/141965178-9439b642-c125-42c0-81d0-f1175bcb7ba1.png)

**Comment by pdubroy** [comment]
Thanks for letting me know, and I appreciate the super clear bug report :-)

I've fixed up the duplicated content and the broken link. However, the `ohm:nil` thing is something specific to Nextjournal that I don't know how to resolved. I've emailed the team, hopefully they can tell me how to fix it.

**Comment by customcommander** [comment]
@pdubroy Looks like they fixed the `nil` issue. Thanks for fixing so quickly!

**Comment by pdubroy** [comment]
Cool! Thanks go to @mk and crew for the quick fix on Nextjournal :-)

**Comment by mk** [comment]
Oh yes, @zampino fixed it promptly and I said I’d write you @pdubroy but then forgot. 🙈 Sorry for breaking it in the first place!
