### ISSUE TITLE
How do get a space but exclude newlines ("\n")

### ISSUE THREAD

**Issue by stephano33** [harc/ohm#379]
I love Ohm.js!

However, I find it sometimes hard to define horizontal white space. I.e. whitespace but excluding newline characters.
What is the best way to do that?

My current workaround is this:
`sp = (~"\n" space)*`

But I'm not sure if the negative lookahead will lead to problems down the road, so I'd like to avoid negative lookaheads.

**Comment by pdubroy** [comment]
If you want explicit space skipping, that’s an easy way to do it. If you
want Ohm’s built in implicit space skipping to not swallow new lines, you
can do something similar by redefining the built-in `spaces` rule like so:

```
spaces := (~”\n” space)*
```

There’s no reason to avoid negative lookahead that I know of.

**Comment by pdubroy** [comment]
I'm going to go ahead and close this since it doesn't seem to be an actual issue with Ohm. Please feel free to re-open if you disagree!
