### ISSUE TITLE
BNF

### ISSUE THREAD

**Issue by bytearchive** [harc/ohm#397]
does this thing understands BNF, or maybe a bnf -> ohm converter? or do I have to learn another meta langauge?

**Comment by pdubroy** [comment]
Since the Ohm language is based on [PEGs](https://en.wikipedia.org/wiki/Parsing_expression_grammar), it's not really feasible to directly translate from BNF/EBNF.

So yes, if you'd like to use Ohm, you'll have to learn a new meta language. 😁

**Comment by bytearchive** [comment]
thanks i'll pass
