### ISSUE TITLE
Building a standalone parser

### ISSUE THREAD

**Issue by jareware** [harc/ohm#401]
I'm sorry if this is covered somewhere in the docs, I honestly tried hard to find the answer online... but is it possible to build an Ohm parser into a zero-deps JS module like what you get if you do "Download parser" at https://pegjs.org/online?

**Comment by pdubroy** [comment]
Hi - sorry for not replying sooner. No, this is not something that Ohm directly supports. However, you could do it yourself by using a bundler like [Rollup](https://rollupjs.org/) or [esbuild](https://esbuild.github.io/).
