### ISSUE TITLE
asIteration is missing from the TypeScript types

### ISSUE THREAD

**Issue by ericmorand** [harc/ohm#407]
`asIteration` is in the documentation but I cant' find it in the TypeScript types.

Is it really supported? How can we use it if we don't know on what kind of node it applies and what it returns?

Thanks by advance.

**Comment by pdubroy** [comment]
Good catch — I can add it to the type definitions. Yes, it's supported, and it returns an `IterationNode`.

**Comment by pdubroy** [comment]
Fixed on main. I will try to publish a minor release with the fix soon.
