### ISSUE TITLE
The ecmascript package example can't work

### ISSUE THREAD

**Issue by justinmchase** [harc/ohm#94]
Due to this line:
https://github.com/cdglabs/ohm/blob/master/examples/ecmascript/es5.js#L12

When its installed via package it is no longer a subdirectory of ohm. I think if you just `require('ohm-js')` it should resolve up the directory chain.

But given its a peer dependency it seems like it should probably change it to allow ohm to be passed in via peer also, something like:

```
var ohm = require('ohm-js');
var es = require('ohm-example-ecmascript');
var es5 = es.es5({ ohm: ohm });
...
```

**Comment by pdubroy** [comment]
Ack, thanks for pointing this out. I published that package rather hastily, and clearly didn't test it properly (or at all?).

Thanks for submitting a PR for this (#97).
